-- MySQL Script generated by MySQL Workbench
-- vie 27 nov 2015 13:49:30 CLT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreCargo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCargo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreArea` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idArea`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreUsuario` VARCHAR(45) NULL COMMENT '',
  `apellidoUsuario` VARCHAR(45) NULL COMMENT '',
  `rutUsuario` VARCHAR(30) NULL COMMENT '',
  `passUsuario` VARCHAR(45) NULL COMMENT '',
  `mailUsuario` VARCHAR(45) NULL COMMENT '',
  `cuentaUsuario` VARCHAR(30) NULL COMMENT '',
  `estadoUsuario` TINYINT(1) NULL COMMENT '',
  `Cargo_idCargo` INT NOT NULL COMMENT '',
  `Area_idArea` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  INDEX `fk_Usuario_Cargo1_idx` (`Cargo_idCargo` ASC)  COMMENT '',
  INDEX `fk_Usuario_Area1_idx` (`Area_idArea` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Externo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Externo` (
  `idExterno` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `unidadExterno` VARCHAR(45) NULL COMMENT '',
  `nombreExterno` VARCHAR(45) NULL COMMENT '',
  `apellidoExterno` VARCHAR(45) NULL COMMENT '',
  `cargoExterno` VARCHAR(45) NULL COMMENT '',
  `runExterno` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idExterno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `NUE` INT NOT NULL COMMENT '',
  `fechaIngreso` DATETIME NULL COMMENT '',
  `RUC` VARCHAR(45) NULL COMMENT '',
  `RIT` VARCHAR(45) NULL COMMENT '',
  `direccionFotografia` VARCHAR(60) NULL COMMENT '',
  `fechaOcurrido` DATETIME NULL COMMENT '',
  `lugarLevantamiento` VARCHAR(50) NULL COMMENT '',
  `numeroParte` INT NULL COMMENT '',
  `observaciones` VARCHAR(300) NULL COMMENT '',
  `direccionSS` VARCHAR(50) NULL COMMENT '',
  `delitoRef` VARCHAR(45) NULL COMMENT '',
  `descripcionEspecie` VARCHAR(300) NULL COMMENT '',
  `Externo_idExterno` INT NOT NULL COMMENT '',
  PRIMARY KEY (`NUE`)  COMMENT '',
  INDEX `fk_Formulario_Externo1_idx` (`Externo_idExterno` ASC)  COMMENT '',
  CONSTRAINT `fk_Formulario_Externo1`
    FOREIGN KEY (`Externo_idExterno`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Evidencia` (
  `idTipo_Evidencia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreTipoEvidencia` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipo_Evidencia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evidencia` (
  `idEvidencia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreEvidencia` VARCHAR(45) NULL COMMENT '',
  `Tipo_Evidencia_idTipo_Evidencia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEvidencia`)  COMMENT '',
  INDEX `fk_Evidencia_Tipo_Evidencia1_idx` (`Tipo_Evidencia_idTipo_Evidencia` ASC)  COMMENT '',
  CONSTRAINT `fk_Evidencia_Tipo_Evidencia1`
    FOREIGN KEY (`Tipo_Evidencia_idTipo_Evidencia`)
    REFERENCES `mydb`.`Tipo_Evidencia` (`idTipo_Evidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadena_Custodia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadena_Custodia` (
  `idCadenaCustodia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaIngreso` DATETIME NULL COMMENT '',
  `descripcionEspecie` VARCHAR(300) NULL COMMENT '',
  `Evidencia_idEvidencia` INT NOT NULL COMMENT '',
  `Formulario_NUE` INT NOT NULL COMMENT '',
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCadenaCustodia`)  COMMENT '',
  INDEX `fk_Cadena_Custodia_Evidencia1_idx` (`Evidencia_idEvidencia` ASC)  COMMENT '',
  INDEX `fk_Cadena_Custodia_Formulario1_idx` (`Formulario_NUE` ASC)  COMMENT '',
  INDEX `fk_Cadena_Custodia_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC)  COMMENT '',
  CONSTRAINT `fk_Cadena_Custodia_Evidencia1`
    FOREIGN KEY (`Evidencia_idEvidencia`)
    REFERENCES `mydb`.`Evidencia` (`idEvidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadena_Custodia_Formulario1`
    FOREIGN KEY (`Formulario_NUE`)
    REFERENCES `mydb`.`Formulario` (`NUE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadena_Custodia_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peritaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peritaje` (
  `idPeritaje` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaPeritaje` DATETIME NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPeritaje`)  COMMENT '',
  INDEX `fk_Peritaje_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC)  COMMENT '',
  CONSTRAINT `fk_Peritaje_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peritaje_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Motivo` (
  `idMotivo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipoMotivo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMotivo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Involucrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Involucrado` (
  `idInvolucrado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaEntrega` DATETIME NULL COMMENT '',
  `Tipo_Motivo_idMotivo` INT NOT NULL COMMENT '',
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL COMMENT '',
  `Externo_idExterno` INT NOT NULL COMMENT '',
  `Externo_idExterno1` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idInvolucrado`)  COMMENT '',
  INDEX `fk_Involucrado_Tipo_Motivo1_idx` (`Tipo_Motivo_idMotivo` ASC)  COMMENT '',
  INDEX `fk_Involucrado_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC)  COMMENT '',
  INDEX `fk_Involucrado_Externo1_idx` (`Externo_idExterno` ASC)  COMMENT '',
  INDEX `fk_Involucrado_Externo2_idx` (`Externo_idExterno1` ASC)  COMMENT '',
  CONSTRAINT `fk_Involucrado_Tipo_Motivo1`
    FOREIGN KEY (`Tipo_Motivo_idMotivo`)
    REFERENCES `mydb`.`Tipo_Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Externo1`
    FOREIGN KEY (`Externo_idExterno`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Externo2`
    FOREIGN KEY (`Externo_idExterno1`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
