-- MySQL Script generated by MySQL Workbench
-- 11/28/15 17:08:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nombreCargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nombreArea` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `apellidoUsuario` VARCHAR(45) NULL,
  `rutUsuario` VARCHAR(30) NULL,
  `passUsuario` VARCHAR(45) NULL,
  `mailUsuario` VARCHAR(45) NULL,
  `cuentaUsuario` VARCHAR(30) NULL,
  `estadoUsuario` TINYINT(1) NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Cargo1_idx` (`Cargo_idCargo` ASC),
  INDEX `fk_Usuario_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Usuario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Externo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Externo` (
  `idExterno` INT NOT NULL AUTO_INCREMENT,
  `unidadExterno` VARCHAR(45) NULL,
  `nombreExterno` VARCHAR(45) NULL,
  `apellidoExterno` VARCHAR(45) NULL,
  `cargoExterno` VARCHAR(45) NULL,
  `runExterno` VARCHAR(45) NULL,
  PRIMARY KEY (`idExterno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `NUE` INT NOT NULL,
  `fechaIngreso` DATETIME NULL,
  `RUC` VARCHAR(45) NULL,
  `RIT` VARCHAR(45) NULL,
  `direccionFotografia` VARCHAR(60) NULL,
  `fechaOcurrido` DATETIME NULL,
  `lugarLevantamiento` VARCHAR(50) NULL,
  `numeroParte` INT NULL,
  `observaciones` VARCHAR(300) NULL,
  `direccionSS` VARCHAR(50) NULL,
  `delitoRef` VARCHAR(45) NULL,
  `descripcionEspecie` VARCHAR(300) NULL,
  `ultimaEdicion` DATETIME NULL,
  `Externo_idExterno` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`NUE`),
  INDEX `fk_Formulario_Externo1_idx` (`Externo_idExterno` ASC),
  INDEX `fk_Formulario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Formulario_Externo1`
    FOREIGN KEY (`Externo_idExterno`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formulario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Evidencia` (
  `idTipo_Evidencia` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoEvidencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Evidencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evidencia` (
  `idEvidencia` INT NOT NULL AUTO_INCREMENT,
  `nombreEvidencia` VARCHAR(45) NULL,
  `Tipo_Evidencia_idTipo_Evidencia` INT NOT NULL,
  PRIMARY KEY (`idEvidencia`),
  INDEX `fk_Evidencia_Tipo_Evidencia1_idx` (`Tipo_Evidencia_idTipo_Evidencia` ASC),
  CONSTRAINT `fk_Evidencia_Tipo_Evidencia1`
    FOREIGN KEY (`Tipo_Evidencia_idTipo_Evidencia`)
    REFERENCES `mydb`.`Tipo_Evidencia` (`idTipo_Evidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadena_Custodia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadena_Custodia` (
  `idCadenaCustodia` INT NOT NULL AUTO_INCREMENT,
  `fechaIngreso` DATETIME NULL,
  `descripcionEspecie` VARCHAR(300) NULL,
  `observaciones` VARCHAR(300) NULL,
  `ultimaEdicion` DATETIME NULL,
  `Evidencia_idEvidencia` INT NOT NULL,
  `Formulario_NUE` INT NOT NULL,
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL,
  PRIMARY KEY (`idCadenaCustodia`),
  INDEX `fk_Cadena_Custodia_Evidencia1_idx` (`Evidencia_idEvidencia` ASC),
  INDEX `fk_Cadena_Custodia_Formulario1_idx` (`Formulario_NUE` ASC),
  INDEX `fk_Cadena_Custodia_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC),
  CONSTRAINT `fk_Cadena_Custodia_Evidencia1`
    FOREIGN KEY (`Evidencia_idEvidencia`)
    REFERENCES `mydb`.`Evidencia` (`idEvidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadena_Custodia_Formulario1`
    FOREIGN KEY (`Formulario_NUE`)
    REFERENCES `mydb`.`Formulario` (`NUE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadena_Custodia_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peritaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peritaje` (
  `idPeritaje` INT NOT NULL AUTO_INCREMENT,
  `fechaPeritaje` DATETIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL,
  PRIMARY KEY (`idPeritaje`),
  INDEX `fk_Peritaje_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC),
  CONSTRAINT `fk_Peritaje_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peritaje_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Motivo` (
  `idMotivo` INT NOT NULL AUTO_INCREMENT,
  `tipoMotivo` VARCHAR(45) NULL,
  PRIMARY KEY (`idMotivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Involucrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Involucrado` (
  `idInvolucrado` INT NOT NULL AUTO_INCREMENT,
  `fechaEntrega` DATETIME NULL,
  `Tipo_Motivo_idMotivo` INT NOT NULL,
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL,
  `Externo_idExterno` INT NOT NULL,
  `Externo_idExterno1` INT NOT NULL,
  PRIMARY KEY (`idInvolucrado`),
  INDEX `fk_Involucrado_Tipo_Motivo1_idx` (`Tipo_Motivo_idMotivo` ASC),
  INDEX `fk_Involucrado_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC),
  INDEX `fk_Involucrado_Externo1_idx` (`Externo_idExterno` ASC),
  INDEX `fk_Involucrado_Externo2_idx` (`Externo_idExterno1` ASC),
  CONSTRAINT `fk_Involucrado_Tipo_Motivo1`
    FOREIGN KEY (`Tipo_Motivo_idMotivo`)
    REFERENCES `mydb`.`Tipo_Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Externo1`
    FOREIGN KEY (`Externo_idExterno`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Involucrado_Externo2`
    FOREIGN KEY (`Externo_idExterno1`)
    REFERENCES `mydb`.`Externo` (`idExterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edicion_Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edicion_Formulario` (
  `idEdicion` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Formulario_NUE` INT NOT NULL,
  `fechaEdicion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEdicion`),
  INDEX `fk_Edicion_Formulario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Edicion_Formulario_Formulario1_idx` (`Formulario_NUE` ASC),
  CONSTRAINT `fk_Edicion_Formulario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edicion_Formulario_Formulario1`
    FOREIGN KEY (`Formulario_NUE`)
    REFERENCES `mydb`.`Formulario` (`NUE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edicion_Cadena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edicion_Cadena` (
  `idEdicion_Cadena` INT NOT NULL,
  `fechaEdicion` DATETIME NULL,
  `Cadena_Custodia_idCadenaCustodia` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEdicion_Cadena`),
  INDEX `fk_Edicion_Cadena_Cadena_Custodia1_idx` (`Cadena_Custodia_idCadenaCustodia` ASC),
  INDEX `fk_Edicion_Cadena_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Edicion_Cadena_Cadena_Custodia1`
    FOREIGN KEY (`Cadena_Custodia_idCadenaCustodia`)
    REFERENCES `mydb`.`Cadena_Custodia` (`idCadenaCustodia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edicion_Cadena_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
